"""Settings for the HAP-E data analysis page (Biber features and sentiment).

Ported from the constants in HAP-E_Researcher_website.html. Edit wording, topic names,
groupings and colors here, not in app_pages/hape_analysis.py.
"""

PAGE_INTRO = (
    "A comparative guide to the stylistic and emotional differences in text "
    "generated by large language models compared to human authors."
)
DATA_NOTE = (
    "This page uses data from HAP-E-2, the Human-AI Parallel English corpus: "
    "https://huggingface.co/datasets/browndw/human-ai-parallel-corpus-2"
    "\n\nSelect a topic to view a side-by-side comparison of human writing and LLM-generated text." \
    "Then, use the drop-down menu to select features to highlight." \
    "\n\nAccording to Reinhart et al. (2025), large language models tend to use more nominal density (nominalizations) and exhibit less modulation of stance and confidence (hedging/boosting) compared to human authors."
)

# One label per academic paragraph pair, in the order they appear in biber_paragraphs.json
# (most divergent first). Double-check these by hand.
TOPIC_LABELS = [
    "Soil characteristics & fertilizer response",
    "Divertor neutral dynamics in JET plasmas",
    "Lifetime earnings profiles & loan repayment",
    "Airborne carbonyls & lung-cell inflammation",
    "Measuring ethical consumer behaviour",
    "Satellite retrieval of coastal water quality",
    "In vitro–in vivo extrapolation in risk assessment",
    "Cavitation to remove CRUD in nuclear systems",
    "Germline-targeting immunogens for HIV",
    "Aluminium grain-refiner efficiency",
]

# Bundles of the features most discussed in Reinhart et al. (2025) and DeLuca et al. (2025).
# Painted as a highlight on matching tokens. "color" is the accent (dots, borders); "hl" gives the
# highlight fill and text for each theme, picked so the text stays above 7:1 on its fill. Colorblind-safe hues.
THEMATIC_GROUPS = {
    "nominal_density": {
        "label": "Nominal density",
        "color": "#009e73",
        "hl": {"light": ("#9fe3c4", "#14151a"), "dark": ("#14634a", "#f4f2ea")},
        "features": [
            "f_14_nominalizations", "f_15_gerunds",
            "f_25_present_participle", "f_28_present_participle_whiz",
        ],
    },
    "hedging_boosting": {
        "label": "Hedging & Boosting",
        "color": "#1b8dc5",
        "hl": {"light": ("#a8d4f5", "#14151a"), "dark": ("#1d4f7e", "#f4f2ea")},
        "features": [
            "f_47_hedges", "f_48_amplifiers", "f_49_emphatics", "f_46_downtoners",
            "f_52_modal_possibility", "f_53_modal_necessity", "f_56_verb_private", "f_58_verb_seem",
        ],
    },
    "agentless_impersonal": {
        "label": "Agentless passives",
        "color": "#d55e00",
        "hl": {"light": ("#ffc999", "#14151a"), "dark": ("#8a3d0a", "#f4f2ea")},
        "features": [
            "f_17_agentless_passives", "f_18_by_passives", "f_20_existential_there",
            "f_26_past_participle", "f_09_pronoun_it",
        ],
    },
}

BIBER_LEGEND = (
    "<strong>Linguistic features</strong> bundle Biber features by the contrasts most cited in "
    "Reinhart et al. (2025): nominal density, hedging &amp; boosting, and agentless/impersonal "
    "constructions. Choose a group to highlight its features in both passages."
)

# ── Sentiment ────────────────────────────────────────────────────────────────
SENTIMENT_INTRO = (
    "Every sentence in the corpus was scored for 27 emotions using Google's GoEmotions sentiment classifier. "
    "The ranking below shows which emotions a model expresses <em>more</em> or <em>less</em> "
    "than human writers across all six genres; the paired academic passages show that contrast "
    "in a single parallel sample. Select any emotion to highlight where it fires in the passages."
)

# Valence colors: green / orange / blue, colorblind-safe and distinct from the Biber backgrounds.
VALENCE_COLOR = {"positive": "#2d7a4f", "negative": "#c1440e", "ambiguous": "#5a6e9e"}

AUTHOR_DISPLAY = {
    "human": "Human", "gpt-4o": "GPT-4o", "gpt-4": "GPT-4", "claude": "Claude",
    "llama": "Llama", "gemma-2-9b-it": "Gemma-2-9B-it",
}

AI_GROUP_LABELS = {
    "machine": "All LLMs",
    "gemma": "Gemma", "gpt": "GPT", "llama": "Llama", "claude": "Claude",
    "gemma-2-9b": "Gemma 2 9B", "gemma-2-9b-it": "Gemma 2 9B-it",
    "gemma-2-27b": "Gemma 2 27B", "gemma-2-27b-it": "Gemma 2 27B-it",
    "gpt-4o": "GPT-4o", "gpt-4o-mini": "GPT-4o mini", "gpt-5-mini": "GPT-5 mini",
    "llama-3-8b": "Llama 3 8B", "llama-3-8b-instruct": "Llama 3 8B Instruct",
    "llama-3-70b": "Llama 3 70B", "llama-3-70b-instruct": "Llama 3 70B Instruct",
    "claude-haiku-4-5": "Claude Haiku 4.5",
    "gemini-3.1-pro": "Gemini 3.1 Pro",
}

# Family aggregates first, each followed by its individual models.
AI_GROUP_ORDER = [
    "machine",
    "gemma", "gemma-2-9b", "gemma-2-9b-it", "gemma-2-27b", "gemma-2-27b-it",
    "gpt", "gpt-4o", "gpt-4o-mini", "gpt-5-mini",
    "llama", "llama-3-8b", "llama-3-8b-instruct", "llama-3-70b", "llama-3-70b-instruct",
    "claude", "claude-haiku-4-5",
]
AI_FAMILIES = {"machine", "gemma", "gpt", "llama", "claude"}

TOP_N_EMOTIONS = 12  # how many emotions to rank in the loadings chart
